title: Tensorflow
author: Aditya yogi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Tensorflow tutorials and how to contribute towards its developmemt

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
